-- SCOTT.MINI_MEMBER definition

CREATE TABLE "SCOTT"."MINI_MEMBER" 
   (	"USERNUMBER" NUMBER(4,0), 
	"USERID" VARCHAR2(40), 
	"PASSWD" VARCHAR2(20), 
	"NAME" VARCHAR2(20), 
	"AGE" NUMBER(2,0), 
	"EMAIL" VARCHAR2(30), 
	"PHONENUMBER" VARCHAR2(15), 
	"ADDRESS" VARCHAR2(50), 
	"DETAILADDRESS" VARCHAR2(50), 
	"SEX" VARCHAR2(10), 
	"HABIT" VARCHAR2(70), 
	"REGISTERTIME" DATE, 
	"LOGINTIME" DATE, 
	"ADMIN" CHAR(1) DEFAULT 'N', 
	"BIRTHDAY" DATE, 
	"LOCKED" CHAR(1) DEFAULT 'N', 
	"FAILCOUNT" NUMBER(1,0) DEFAULT 0, 
	"DELETEYN" CHAR(1) DEFAULT 'N', 
	 CONSTRAINT "MEMBER_PK" PRIMARY KEY ("USERNUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "MINI_MEMBER_UNIQUE" UNIQUE ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "SCOTT"."MINI_MEMBER_UNIQUE" ON "SCOTT"."MINI_MEMBER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "SCOTT"."MEMBER_PK" ON "SCOTT"."MINI_MEMBER" ("USERNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
  
  CREATE SEQUENCE SCOTT.SEQ_MINI_NUMBER INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE NOORDER